export const data = [
    { "key": "First Name", "value": "John" },
    { "key": "Last Name", "value": "Snow" },
    { "key": "Full Name", "value": "John Snow" },
    { "key": "Full date of birth", "value": "1990-05-15" },
    { "key": "Birth month mm", "value": "05" },
    { "key": "Birth day dd", "value": "15" },
    { "key": "Birth year yyyy", "value": "1990" },
    { "key": "Gender", "value": "Male" },
    { "key": "Phone", "value": "+1 (555) 123-4567" },
    { "key": "Mobile", "value": "+1 (555) 123-4567" },
    { "key": "Email", "value": "john.snow@example.com" },
    { "key": "Full address", "value": "123 Winterfell Lane, Castle Black, The North, Westeros, 01010" },
    { "key": "City", "value": "Castle Black" },
    { "key": "Country", "value": "The North" },
    { "key": "Zip code / postal code", "value": "01010" },
    { "key": "Social Security Number (SSN)", "value": "123-45-6789" },
    { "key": "Health Insurance", "value": "123456" },
    { "key": "Primary Care Physician", "value": "Dr. Maester Aemon" },
    { "key": "Allergies", "value": "Penicillin" },
    { "key": "Current Medication", "value": "None" },
    { "key": "Blood Type", "value": "O+" },
    { "key": "Emergency Contact", "value": "Arya Stark (+1 (555) 987-6543)" },
    { "key": "Current Employer", "value": "Night's Watch" },
    { "key": "Job Title", "value": "Lord Commander" },
    { "key": "Department", "value": "Defence" },
    { "key": "Compensation", "value": "$100k" },
    { "key": "Salary", "value": "$100k" },
    { "key": "Desired salary", "value": "$100k" },
    { "key": "Work Email", "value": "john.snow@thenightswatch.org" },
    { "key": "Work Phone Number", "value": "+1 (555) 890-1234" },
    { "key": "Office Address", "value": "The Wall, Castle Black, The North, Westeros, 01010" },
    { "key": "Highest Degree Obtained", "value": "Bachelor of Arms" },
    { "key": "Earliest start date, begin date", "value": "July 2024" },
    { "key": "Times available to work", "value": "Mon-Fri 9am to 5pm" },
    { "key": "University", "value": "The Citadel" },
    { "key": "Graduation Year", "value": "2012" },
    { "key": "Major", "value": "Battle Tactics and Leadership" },
    { "key": "Passport Number", "value": "W12345678" },
    { "key": "Nationality", "value": "Westerosi" },
    { "key": "Frequent Flyer Number", "value": "56789-123" },
    { "key": "Known Traveler Number (KTN)", "value": "KTN1234567890" },
    { "key": "Preferred Airlines", "value": "Royal Air, Dragonfly Air" },
    { "key": "Destination Preferences", "value": "Dragonstone, King's Landing, Winterfell" },
    { "key": "Bank Name", "value": "Iron Bank of Braavos" },
    { "key": "Account Number", "value": "000123456789" },
    { "key": "Routing Number", "value": "110000000" },
    { "key": "Credit Card Type", "value": "Visa" },
    { "key": "Credit Card Number", "value": "4111 1111 1111 1111" },
    { "key": "Expiration Date", "value": "01/25" },
    { "key": "CVV", "value": "123" },
    { "key": "LinkedIn", "value": "https://linkedin.com/in/johnsnow" },
    { "key": "Github", "value": "https://github.com/johnsnow" },
    { "key": "Portfolio", "value": "https://portfolio.com/art/johnsnow" },
    { "key": "Twitter", "value": "https://twitter.com/johnsnow_nw" },
    { "key": "Facebook", "value": "https://facebook.com/john.snow.nightswatch" },
    { "key": "Instagram", "value": "https://instagram.com/lordcommander_snow" },
    { "key": "Favorite Food", "value": "Roast Direwolf" },
    { "key": "Hobbies", "value": "Swordfighting, Horse Riding, Exploring the North" },
    { "key": "Pet Name", "value": "Ghost" },
    { "key": "Pet Type", "value": "Direwolf" },
    { "key": "Languages Spoken", "value": "Common Tongue, Dothraki, Valyrian" }
]
